spring.application.name=backend

# From boot_react_app/backend/Dockerfile 에서 넘어온 값이 적용됨
# application.properties 에 파일에 설정된 프로퍼티는 @Value 또는 Environment 등을 이용해 읽을 수 있습니다. (AppConfig 참고)
spring.api.key=${SPRING_API_KEY}  