# 최근 docker-compose 버전sms qjwjsdmf wkrtjdgkwl dksgtmqslek.
# version: 3.8

# .env 파일과 동일한 경로에 있는 docker-compose.yml 파일을 읽습니다.
# .env 파일을 잘 읽었는지 확인하려면 docker-compose config 명령을 내립니다.
services:
#    environment:
#      SPRING_API_KEY: ${SPRING_API_KEY}
  backend:
    container_name: backend-container
    build:  # Dockerfile을 이용한 도커 이미지를 빌드
      context: ./backend # Dockerfile 이 있는 경로
      args:   # Dockerfile 에 있는 ARG SPRING_API_KEY 으로 보내는 값
        - SPRING_API_KEY=${SPRING_API_KEY} # ${SPRING_API_KEY}는 .env 파일에 있는 값으로 대체됩니다.
    ports:
      - "8080:8080"

  frontend:
    container_name: front-container
    build: 
      context: ./frontend
      args:
        - REACT_APP_API_KEY=${REACT_APP_API_KEY}  # from boot_react_app/.env
    ports:
      - "80:80"
    environment:
      WAIT_HOSTS: backend:8080
    depends_on:
      - backend